### ISSUE TITLE
Add anchor to each heading

### ISSUE THREAD

**Issue by crstn** [SDI-SPIDER/toolkit#5]
… so it is possible to directly link to it. Could be done the same way Wikipedia does it: When you hover over an element, a small link icon appears that copies the direct URL when clicked.

**Comment by crstn** [comment]
Not quite sure how to do this, since all our headings are also links that already do something when clicked on. Maybe add a link icon, like [this one](https://icons.getbootstrap.com/icons/link-45deg/)?

**Comment by markpanek95** [comment]
fixed in df65dc9
